### ISSUE TITLE
[idea] make imports section optional

### ISSUE THREAD

**Issue by skabashnyuk** [maxandersen/jbang#72]
The idea is to make the user focus on coding and omit necessarily of thinking about imports.  
The idea is to reduce the time that is needed to `Google  something-> Find it on StackOverflow-> paste it in editor -> run it `

The way how do I see the possible implementation is to scan the entire classpath, grab all possible classes, add them all to imports, let the compiler decide what is needed and what can be removed in the real class.

WDYT?

**Comment by maxandersen** [comment]
I like the idea and thought similar but the problem is that if you do that you basically break any other tools that you want to use with the script.

example:

```
//DEPS com.fasterxml.jackson.core:jackson-databind:2.2.3

// no imports

public class noimports {

    public static void main(String... args) {
        <|>
    }
}
```

now - if you put your cursor at <|> and now try to do a content assist no IDE will know what to here...

also - the amount of imports we end up swizzling in for something like fast jackson is 149 individual class imports or 11 .* package imports.

I think its better we let the IDE's help here as they are quite good at identifiying the right import based on just having the classname which the user found in an example.

**Comment by skabashnyuk** [comment]
sounds reasonable.
